# Generated by Django 4.0.4 on 2022-06-19 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'max_length': 'Очень большая длина'}, help_text='Название для слайда до 100 символов,обязательно к заполнению', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Название слайда')),
                ('title', models.CharField(blank=True, error_messages={'max_length': 'Очень большая длина'}, help_text='до 150 символов,необязательное поле', max_length=150, validators=[django.core.validators.MaxLengthValidator(150)], verbose_name='Заголовок слайда')),
                ('description', models.CharField(blank=True, error_messages={'max_length': 'Очень большая длина'}, help_text='до 150 символов,необязательное поле', max_length=150, validators=[django.core.validators.MaxLengthValidator(150)], verbose_name='Текст под заголовком')),
                ('slide_img', models.ImageField(help_text='изображение обрежется до 1920х1024рх, поэтому брать лучше большое', upload_to='slider/', verbose_name='Добавить изображение')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
    ]
